### ISSUE TITLE
Поддержка Laravel 5.6?

### ISSUE THREAD

**Issue by mssmaks** [atehnix/laravel-vk-requester#10]
Здравствуйте, планируется ли обновление до laravel 5.6?

**Comment by ghost** [comment]
Приветствую! 
Выпущен свежий релиз с поддержкой Laravel 5.6.

К сожалению, на полноценную поддержку, тестирование версий и развитие пакета у меня сейчас нет времени.
Но, после беглой оценки, не нашел причин, мешающих использовать пакет с версией Laravel 5.6.
Потому, 5.6 добавлен в список поддерживаемых версий фреймворка.

Спасибо за напоминание)
