### ISSUE TITLE
Поддержка laravel 5.7

### ISSUE THREAD

**Issue by mssmaks** [atehnix/laravel-vk-requester#11]
Снова здравствуйте. Интересует поддержка laravel 5.7.

**Comment by andreich1980** [comment]
А что, не работает?

**Comment by mssmaks** [comment]
Не работает сам composer update, так как в пакете зависимости только до 5.6 включительно

**Comment by ghost** [comment]
Добавлена поддержка Laravel 5.7.
Спасибо за очередное напоминание.=)
