### ISSUE TITLE
Laravel 6.0 compatibility

### ISSUE THREAD

**Issue by nikitabuida** [atehnix/laravel-vk-requester#15]
Please upgrade to support for Laravel 6.0.
Looks like 6.0 doesn't introduce any breaking features concerning your package.

**Comment by ghost** [comment]
Okay. :+1: 
Version 1.0.0 released with Laravel 6 compatibility (theoretical). =)
However, please inform if incompatible changes of framework are found.

**Comment by nikitabuida** [comment]
Thanks a lot!

**Comment by nikitabuida** [comment]
Sadly still doesn't work

 Problem 1
    - Installation request for atehnix/laravel-vk-requester ^1.0 -> satisfiable by atehnix/laravel-vk-requester[v1.0.0].
    - Conclusion: remove laravel/framework v6.0.3
    - Conclusion: don't install laravel/framework v6.0.3
    - atehnix/laravel-vk-requester v1.0.0 requires laravel/framework ^5.2,<7.0 -> **satisfiable by laravel/framework[5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev].**

**Comment by ghost** [comment]
Oh, sorry. This is now fixed.
(v1.0.1)

**Comment by nikitabuida** [comment]
Works great now. Many thanks!
