### ISSUE TITLE
Как получить имя пользователя и другие его данные?

### ISSUE THREAD

**Issue by slower1337** [atehnix/laravel-vk-requester#16]
_**laravel-vk-requester:** https://github.com/atehnix/laravel-vk-requester_

Когда я логинюсь, то я хочу вывести все данные о пользователе, но я получаю только его id и сгенерировавшийся токен.

Вот код с страницы, куда я попадаю после входа:
`echo '<pre>'; print_r($auth->getUserData(Request::get('code'))); echo '</pre>';`

Вот что я вижу:
`Array`
`(`
    `[access_token] => 0ae97e95fb274....`
    `[expires_in] => 0`
    `[user_id] => 181510118`
`)`

Когда я использовал обычный пхп, то я это делал так: `$auth->first_name`.
Но тут оно, конечно же, не будет работать.

**Резюмирую,** у меня есть user_id. Как мне получить его имя, фамилию, фото профиля и все остальные доступные данные о пользователе?

---
(Отредактировано @atehnix: скрыл токен от чужих глаз)

**Comment by ghost** [comment]
В соответствии с документацией API, получить информацию о пользователе можно отправив запрос с методом: "users.get" от имени пользователя (с передачей токена).

Подробнее: https://vk.com/dev.php?method=users.get

**Comment by atehnix** [comment]
Вопрос не относится к проблемам/предложениям по функционалу пакета.
