### ISSUE TITLE
Как изменить время истечения токена?

### ISSUE THREAD

**Issue by slower1337** [atehnix/laravel-vk-requester#17]
_**laravel-vk-requester:** https://github.com/atehnix/laravel-vk-requester_

После того, как я логинюсь, а затем перезагружаю страницу, то я автоматически выхожу.
Это все происходит из-за того, что время токена заканчивается.

_Как я это узнал?_
Если после того, как я залогинюсь, я выведу данные , которые мне доступны, то я увижу, что время истечения токена = 0.
`[expires_in] => 0`

Я пробовал в `vendor/atehnix/vkclient/src/Auth.php` и `vendor/atehnix/vkclient/src/Client.php` поменять `const API_TIMEOUT = 0.0;` и `const TIMEOUT = 0;` на другие значения, однако это не помогло

**Резюмирую:** У меня токен истекает через 0с. после его создания. Как задать другое время его истечения?

**Comment by ghost** [comment]
Пакет предназначен для выполнения запросов к API, а не для аутентификации пользователя в Laravel.
(если требуется именно аутентификация через VK, можно например воспользоваться пакетом [socialiteproviders/vkontakte](https://socialiteproviders.netlify.com/providers/v-kontakte.html))

Большинство API-методов VK требуют передачи токена вместе с запросом. Указать токен при создании запроса можно как написано в Readme пакета: [atehnix/laravel-vk-requester#добавление-запроса-в-очередь](https://github.com/atehnix/laravel-vk-requester#%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0-%D0%B2-%D0%BE%D1%87%D0%B5%D1%80%D0%B5%D0%B4%D1%8C)

Но пакет не навязывает вам как именно хранить токены. Получив API-токен вы должны самостоятельно решить где и как вы будете его хранить. [atehnix/laravel-vk-requester#пример-получения-токена](https://github.com/atehnix/laravel-vk-requester#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80-%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D1%82%D0%BE%D0%BA%D0%B5%D0%BD%D0%B0)

Значение `"expires_in": 0` соответствует бессрочному времени жизни токена.
Подробнее: [https://vk.com/dev/authcode_flow_user](https://vk.com/dev/authcode_flow_user?f=4.%20%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%20access_token)

**Comment by slower1337** [comment]
Спасибо Вам огромное за уделенное время, теперь я разобрался! Удачи Вам.20.01.2020, 16:40, "Andrey Sosnov" <notifications@github.com>:Пакет предназначен для выполнения запросов к API, а не для аутентификации пользователя в Laravel.
(если требуется именно аутентификация через VK, можно например воспользоваться пакетом socialiteproviders/vkontakte)
Большинство API-методов VK требуют передачи токена вместе с запросом. Указать токен при создании запроса можно как написано в Readme пакета: atehnix/laravel-vk-requester#добавление-запроса-в-очередь
Но пакет не навязывает вам как именно хранить токены. Получив API-токен вы должны самостоятельно решить где и как вы будете его хранить. atehnix/laravel-vk-requester#пример-получения-токена
Значение "expires_in": 0 соответствует бессрочному времени жизни токена.
Подробнее: https://vk.com/dev/authcode_flow_user

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Yours faithfully,Artyom Inagamov+79117926305inagamov.ar@yandex.ru
