### ISSUE TITLE
Laravel 7.0 support

### ISSUE THREAD

**Issue by nikitabuida** [atehnix/laravel-vk-requester#18]
Добрый день!
Столкнулся с проблемой что у пакета стоит условие laravel <7.0.
Кажется тут всё также совместимо, так что для поддержки достаточно только условие отредактировать.

**Comment by ghost** [comment]
Готово. ([v1.1.0](https://github.com/atehnix/laravel-vk-requester/releases/tag/v1.1.0))
Спасибо за информацию!

**Comment by nikitabuida** [comment]
Спасибо!
