### ISSUE TITLE
SendBatchHandler does not exist

### ISSUE THREAD

**Issue by Warchiefs** [atehnix/laravel-vk-requester#2]
Выполнение запросов выкидывает ошибку в лог:

`[2016-10-10 07:01:02] local.ERROR: exception 'ReflectionException' with message 'Class App\Handlers\Commands\ATehnix\LaravelVkRequester\Jobs\SendBatchHandler does not exist' in /var/www/order/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
Stack trace:
#0 /var/www/order/vendor/laravel/framework/src/Illuminate/Container/Container.php(741): ReflectionClass->__construct('App\Handlers\Co...')
#1 /var/www/order/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('App\Handlers\Co...', Array)
#2 /var/www/order/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('App\Handlers\Co...', Array)
#3 /var/www/order/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(283): Illuminate\Foundation\Application->make('App\Handlers\Co...')
#4 /var/www/order/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(74): Illuminate\Bus\Dispatcher->resolveHandler(Object(ATehnix\LaravelVkRequester\Jobs\SendBatch))
#5 /var/www/order/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(212): Illuminate\Queue\CallQueuedHandler->failed(Array)
#6 /var/www/order/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(116): Illuminate\Queue\Jobs\Job->failed()
#7 /var/www/order/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(31): Illuminate\Queue\SyncQueue->handleFailedJob(Object(Illuminate\Queue\Jobs\SyncJob))
#8 /var/www/order/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(268): Illuminate\Queue\SyncQueue->push(Object(ATehnix\LaravelVkRequester\Jobs\SendBatch))
#9 /var/www/order/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(243): Illuminate\Bus\Dispatcher->pushCommandToQueue(Object(Illuminate\Queue\SyncQueue), Object(ATehnix\LaravelVkRequester\Jobs\SendBatch))
#10 /var/www/order/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(175): Illuminate\Bus\Dispatcher->dispatchToQueue(Object(ATehnix\LaravelVkRequester\Jobs\SendBatch))
#11 /var/www/order/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(ATehnix\LaravelVkRequester\Jobs\SendBatch))
#12 /var/www/order/vendor/atehnix/laravel-vk-requester/src/Commands/VkRequesterGeneratorCommand.php(48): ATehnix\LaravelVkRequester\Commands\VkRequesterGeneratorCommand->dispatch(Object(ATehnix\LaravelVkRequester\Jobs\SendBatch))
#13 /var/www/order/vendor/laravel/framework/src/Illuminate/Support/Collection.php(135): ATehnix\LaravelVkRequester\Commands\VkRequesterGeneratorCommand->ATehnix\LaravelVkRequester\Commands{closure}(Object(Illuminate\Database\Eloquent\Collection), '257078e242796b8...')
#14 /var/www/order/vendor/atehnix/laravel-vk-requester/src/Commands/VkRequesterGeneratorCommand.php(50): Illuminate\Support\Collection->each(Object(Closure))
#15 [internal function]: ATehnix\LaravelVkRequester\Commands\VkRequesterGeneratorCommand->handle()
#16 /var/www/order/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#17 /var/www/order/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#18 /var/www/order/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/order/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/order/vendor/symfony/console/Application.php(846): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/order/vendor/symfony/console/Application.php(190): Symfony\Component\Console\Application->doRunCommand(Object(ATehnix\LaravelVkRequester\Commands\VkRequesterGeneratorCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/order/vendor/symfony/console/Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/order/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/order/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}

`
Не пойму что делать. Похоже, что пакет кривой.

Стоит:
`"atehnix/laravel-vk-requester": "^0.5.2"`

Laravel 5.1.*
PHP 5.6.19-0+deb8u1

**Comment by ghost** [comment]
Пакет проверялся только на версиях laravel 5.2 и 5.3. 
В Laravel 5.1 Job'ы работали чуть иначе, поэтому они сейчас не поддерживаются пакетом.
Спасибо за информацию. Добавлю laravel 5.2+ в требования.

**Comment by Warchiefs** [comment]
Запустил на 5.1
Надо добавить в SendBatch
use Illuminate\Contracts\Bus\SelfHandling;

И в наследования класса добавить SelfHadling.

**Comment by ghost** [comment]
Да, все верно. Но дело в том, что в Laravel 5.2/5.3 этот интерфейс (SelfHandling) выпилили из фреймворка. Поэтому, нужно либо найти более универсальное решение, либо отказаться от поддержки 5.1.
На данный момент я выбрал второй вариант. Если будут идеи как сделать универсально - буду только рад.
