### ISSUE TITLE
Поддерживается ли работа без очередей?

### ISSUE THREAD

**Issue by flaksp** [atehnix/laravel-vk-requester#3]
Здравствуйте. Подскажите, пожалуйста, поддерживает ли ваш пакет работу с VK API без системы очередей? То бишь в реальном времени. Если поддерживает, могли бы вы, пожалуйста, добавить пример реализации в README?

Спасибо.

**Comment by ghost** [comment]
Да, отправка запросов напрямую поддерживается благодаря зависимости от пакета [atehnix/vk-client](https://github.com/atehnix/vk-client) . Примеры приведены в readme того пакета.

Если требуется **только** отправка напрямую без очередей, то `atehnix/laravel-vk-requester` ставить не обязательно, достаточно установить `atehnix/vk-client`.
