### ISSUE TITLE
При добавлении запроса в очередь ругается на context

### ISSUE THREAD

**Issue by andreich1980** [atehnix/laravel-vk-requester#4]
`SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: vk_requests.context (SQL: insert into "vk_requests" ("method", "parameters", "token", "updated_at", "created_at") values (wall.get, {"owner_id":1}, some_token, 2016-12-01 12:00:33, 2016-12-01 12:00:33))`

Может нужно в migration сделать `$table->text('context')->nullable();`?
Или в примеры добавить это свойство

**Comment by ghost** [comment]
Действительно, это поле должно быть nullable.
По стечению обстоятельств этот нюанс остался незамеченным, т.к. в проекте, где тестировался пакет, был выключен строгий режим БД, :)
Спасибо!
