### ISSUE TITLE
Поддержка Laravel 5.4

### ISSUE THREAD

**Issue by wekser** [atehnix/laravel-vk-requester#5]
При установке на последнию версию Laravel, composer "ругается" на отсутствие поддержки версии 5.4 фреймворка у данного пакета.

**Comment by ghost** [comment]
Пакет не проверялся на Laravel 5.4. В ближайшее время займусь этим и обновлю пакет.
А пока временно добавил версию [dev-laravel54](https://github.com/atehnix/laravel-vk-requester/releases/tag/0.5.5-laravel54) (работоспособность не гарантируется).

Спасибо, что обратили мое внимание! ;)

**Comment by ghost** [comment]
@WekseR добавлена версия 0.6.0 с поддержкой Laravel 5.4.
