### ISSUE TITLE
Получение email вместе с access_token

### ISSUE THREAD

**Issue by MKraust** [atehnix/laravel-vk-requester#7]
Приветствую!
В моем приложении мне необходимо получить email пользователя, авторизовавшегося через ВК. Его можно получить вместе с access_token, указав email в scope. Но такие данные как user_id, expires_in, email просто отсекаются в методе getToken класса Auth.

**Comment by ghost** [comment]
Спасибо за предложение. 
Возможность получения доп.данных вместе с токеном добавлена.

> [atehnix/vk-client/releases/tag/1.3.0](https://github.com/atehnix/vk-client/releases/tag/1.3.0) - Auth: ability to get an access token along with user data.

Для обновления  выполните в вашем проекте:
`composer update atehnix/vk-client'

Получение данных пользователя вместе с токеном:
```php
$data = $auth->getUserData(Request::get('code')); // все данные, возвращаемые API
$token = $data['access_token']; // токен
```

В то же время, поведение `$auth->getToken()` остается прежним для обратной совместимости.
