### ISSUE TITLE
Мне бы постить что либо в группы!

### ISSUE THREAD

**Issue by maxyc** [atehnix/laravel-vk-requester#8]
Нет возможности доработать до такого уровня?

**Comment by ghost** [comment]
Какие методы API использовать - зависит только от вас. 
Никаких ограничений. Все в ваших руках! ;)

Например, для публикации поста на стене группы см. [wall.post](https://vk.com/dev/wall.post)

**Comment by maxyc** [comment]
wall post только для стандалоне
плюс мне надо по крону

**Comment by ghost** [comment]
Да, в VK предусмотрены токены с разным уровнем доступа. 

В описании пакета приведен пример получения токена по варианту [Authorization Code Flow](https://vk.com/dev/authcode_flow_user). Для "wall.post" такой токен, действительно, не подходит. 

Но это лишь пример одного из вариантов получения токена. Никаких ограничений на использование токенов другого уровня доступа в пакете не предусмотрено.

Если у вас есть токен, полученный по варианту [Implicit Flow](https://vk.com/dev/implicit_flow_user) (для standalone приложений), то никаких проблем с методами типа "wall.post" быть не должно.

[например](https://ru.stackoverflow.com/questions/509384/)
