### ISSUE TITLE
Не удаляется очередь с базы

### ISSUE THREAD

**Issue by ExsyDev** [atehnix/laravel-vk-requester#9]
В новом Laravel при запросе VkRequest не удаляется очередь после выполнения, почему? Из-за этого ошибок полно

**Comment by ghost** [comment]
Напишите, пожалуйста, подробнее: 
- полный номер версии Laravel
- что ожидалось, что происходит по факту
- каких  "ошибок полно"

Спасибо.

**Comment by ExsyDev** [comment]
- Версия Laravel 5.5.33
- Ожидалось, что запрос выполнится без ошибок, а в итоге много ошибок и ничего не выполнилось. И каждую минуту много ошибок, одна из которых ниже, которая чаще всего выдается
- SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'attempts' at row 1 (SQL: update `jobs` set `reserved_at` = 1518099253, `attempts` = 256 where `id` = 1285) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'attempts' at row 1 (SQL: update `jobs` set `reserved_at` = 1518099253, `attempts` = 256 where `id` = 1285) at /var/www/siteorg/data/wwwsite.org/vendor/llaravel/framework/src/Illuminate/Database/Connection.php:664, PDOException(code: 22003): SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'attempts' at row 1 at /var/www/siteorg/data/wwwsite.org/vendor/laravel/framework/src/Illuminate/Database/Connection.php:483)
-----
Тут еще: https://pastebin.com/BNdTK6UT

**Comment by ghost** [comment]
При запуске воркера для очереди, укажите максимальное кол-во попыток. 
[см. тут подробнее](https://laravel.com/docs/5.5/queues#max-job-attempts-and-timeout)

Судя по всему, какой-то из запросов к API оканчивается неудачей и повторяется до тех пор, пока не превысит максимальное значение, которое может вместить поле attempts (попытки) в таблице `jobs`. 

Таким образом, приведенная выше ошибка является не причиной проблемы, а ее следствием. Проверьте корректность вашего запроса в соответствии с [документацией VK API](https://vk.com/dev/methods).

Если проблема появилась не сразу, а внезапно, то вполне возможно, что в VK API произошли изменения. Проверьте [историю изменений](https://vk.com/dev/versions). 

Либо изменились права на объекты, фигурирующие в запросе.

**Comment by ExsyDev** [comment]
Я попробовал сделать это на другом домене и запрос выполнился без ошибок, но очередь в базе из таблицы jobs так и не удалилась. Почему?

**Comment by Dronax** [comment]
Также советую обновить инструкцию по установке, команда:

`php artisan vendor:publish --provider=ATehnix\LaravelVkRequester\VkRequesterServiceProvider`

Не создает конфиги и миграции.

**Comment by ghost** [comment]
>очередь в базе из таблицы jobs так и не удалилась

К сожалению, слишком мало данных для выяснения причины. 

Внутреннее устройство работы очередей Laravel (и чистка таблицы jobs, в частности) выходит за рамки обязанностей данного пакета. 

Тем не менее, спасибо за сообщение!
Если мне удастся воспроизвести проблему и выяснить ее причины, я сообщу дополнительно.
